/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/request-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send passwordless login link */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RequestLinkRequest"];
                };
            };
            responses: {
                /** @description Link queued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RequestLinkResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify email link and issue session token */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VerifyLinkRequest"];
                };
            };
            responses: {
                /** @description Session issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VerifyLinkResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current session and reviewer capability */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
                /** @description Auth required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create order draft */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrderRequest"];
                };
            };
            responses: {
                /** @description Order created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateOrderResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Auth required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Reading profile not enabled */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{orderId}/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Stripe checkout session */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path: {
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Checkout response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckoutResponse"];
                    };
                };
                /** @description Auth required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Order not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Character selection required or order not eligible for checkout */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{orderId}/mark-paid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark order paid (fallback-only) and trigger build */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                    /** @description Required when mock LLM or mock image providers are enabled. Used to explicitly authorize intentional mock runs. */
                    "X-Mock-Run-Tag"?: string;
                };
                path: {
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Build started */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MarkPaidResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Auth required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Mock checkout disabled */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stripe webhook receiver */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description Webhook handled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StripeWebhookResponse"];
                    };
                };
                /** @description Invalid signature or payload */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get order status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Order state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponse"];
                    };
                };
                /** @description Auth required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/books/{bookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get book payload */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bookId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Book details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookResponse"];
                    };
                };
                /** @description Auth required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/books/{bookId}/character": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current character approval state for a book */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bookId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Character approval state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookCharacterResponse"];
                    };
                };
                /** @description Auth required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Book not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/books/{bookId}/character/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate one more character candidate for parent review */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bookId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["GenerateCharacterCandidateRequest"];
                };
            };
            responses: {
                /** @description Updated character approval state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookCharacterResponse"];
                    };
                };
                /** @description Auth required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Book not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Character workflow unavailable or attempt cap reached */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Character description required */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/books/{bookId}/character/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select one character candidate as the canonical reference */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bookId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SelectCharacterRequest"];
                };
            };
            responses: {
                /** @description Updated character approval state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookCharacterResponse"];
                    };
                };
                /** @description Auth required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Book or candidate not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Character workflow unavailable */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List open or historical review cases */
        get: {
            parameters: {
                query?: {
                    status?: "open" | "resolved" | "rejected" | "retrying";
                    stage?: "text_moderation" | "image_safety" | "image_qa" | "finalize_gate";
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Review case queue */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewQueueResponse"];
                    };
                };
                /** @description Auth required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Reviewer access required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/cases/{caseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one review case with page QA details */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    caseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Review case detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewCaseDetailResponse"];
                    };
                };
                /** @description Auth required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Reviewer access required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Review case not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/cases/{caseId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a review case and resume the pipeline */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    caseId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ReviewActionRequest"];
                };
            };
            responses: {
                /** @description Review approved and pipeline resumed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewActionResponse"];
                    };
                };
                /** @description Auth required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Reviewer access required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Review case not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Review case is not open */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/cases/{caseId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a review case and fail the book */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    caseId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReviewActionRequest"];
                };
            };
            responses: {
                /** @description Review rejected */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewActionResponse"];
                    };
                };
                /** @description Auth required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Reviewer access required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Review case not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Review case is not open */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/cases/{caseId}/pages/{pageId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry one page image from a review case */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    caseId: string;
                    pageId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReviewActionRequest"];
                };
            };
            responses: {
                /** @description Page retry queued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewActionResponse"];
                    };
                };
                /** @description Auth required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Reviewer access required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Review case or page not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Retry not allowed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/books/{bookId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get signed download URL */
        get: {
            parameters: {
                query?: {
                    format?: "pdf";
                };
                header?: never;
                path: {
                    bookId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Signed URL */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DownloadResponse"];
                    };
                };
                /** @description Auth required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description PDF not ready */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/child-profiles/{childProfileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete child profile and queue artifact purge */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    childProfileId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deletion queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteChildProfileResponse"];
                    };
                };
                /** @description Auth required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Child profile not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
        };
        RequestLinkRequest: {
            /** Format: email */
            email: string;
        };
        RequestLinkResponse: {
            ok: boolean;
            sent: boolean;
        };
        VerifyLinkRequest: {
            token: string;
        };
        VerifyLinkResponse: {
            token: string;
            user: {
                /** Format: uuid */
                id: string;
                /** Format: email */
                email: string;
            };
        };
        SessionResponse: {
            user: {
                /** Format: uuid */
                id: string;
                /** Format: email */
                email: string;
            };
            capabilities: {
                canReview: boolean;
            };
        };
        CreateOrderRequest: {
            childFirstName: string;
            pronouns: string;
            ageYears: number;
            /** @enum {string} */
            moneyLessonKey: "prices_change" | "jar_saving_limits" | "new_money_unfair" | "keep_what_you_earn" | "better_rules";
            /** @enum {string} */
            storyMode: "sound_money_implicit" | "bitcoin_reveal_8020" | "bitcoin_forward";
            interestTags: string[];
            /** @enum {string} */
            readingProfileId: "read_aloud_3_4" | "early_decoder_5_7" | "independent_8_10";
            characterDescription: string;
        };
        CreateOrderResponse: {
            /** Format: uuid */
            orderId: string;
            /** Format: uuid */
            bookId: string;
            /** Format: uuid */
            childProfileId: string;
            /** @enum {string} */
            status: "created";
            /** @enum {string} */
            checkoutMode: "stripe";
            /** @enum {string} */
            storyMode: "sound_money_implicit" | "bitcoin_reveal_8020" | "bitcoin_forward";
        };
        CheckoutResponse: {
            /** Format: uuid */
            orderId: string;
            /** Format: uuid */
            bookId: string;
            /** @enum {string} */
            status: "created" | "checkout_pending" | "paid" | "building" | "needs_review" | "ready" | "failed" | "refunded";
            checkoutUrl: string | null;
            stripeSessionId: string | null;
            message?: string;
        };
        GenerateCharacterCandidateRequest: {
            characterDescription?: string;
        };
        SelectCharacterRequest: {
            /** Format: uuid */
            imageId: string;
        };
        BookCharacterResponse: {
            /** Format: uuid */
            bookId: string;
            characterDescription: string;
            /** Format: uuid */
            selectedCharacterImageId: string | null;
            selectedCharacterImageUrl: string | null;
            generationCount: number;
            maxGenerations: number;
            remainingGenerations: number;
            canGenerateMore: boolean;
            candidates: {
                /** Format: uuid */
                imageId: string;
                imageUrl: string | null;
                createdAt: string;
                isSelected: boolean;
            }[];
        };
        MarkPaidResponse: {
            ok: boolean;
            /** Format: uuid */
            orderId: string;
            /** Format: uuid */
            bookId: string;
            executionArn: string | null;
            started: boolean;
        };
        StripeWebhookResponse: {
            ok: boolean;
            stripeEventId: string;
            stripeEventType: string;
            processingStatus: string;
            executionArn: string | null;
        };
        OrderResponse: {
            /** Format: uuid */
            orderId: string;
            /** @enum {string} */
            status: "created" | "checkout_pending" | "paid" | "building" | "needs_review" | "ready" | "failed" | "refunded";
            createdAt: string;
            /** Format: uuid */
            bookId: string;
            /** @enum {string} */
            bookStatus: "draft" | "building" | "needs_review" | "ready" | "failed";
            /** Format: uuid */
            childProfileId: string;
            /** @enum {string} */
            storyMode: "sound_money_implicit" | "bitcoin_reveal_8020" | "bitcoin_forward";
        };
        BookResponse: {
            /** Format: uuid */
            bookId: string;
            /** @enum {string} */
            status: "draft" | "building" | "needs_review" | "ready" | "failed";
            childFirstName: string;
            /** @enum {string} */
            readingProfileId: "read_aloud_3_4" | "early_decoder_5_7" | "independent_8_10";
            /** @enum {string} */
            moneyLessonKey: "prices_change" | "jar_saving_limits" | "new_money_unfair" | "keep_what_you_earn" | "better_rules";
            /** @enum {string} */
            storyMode: "sound_money_implicit" | "bitcoin_reveal_8020" | "bitcoin_forward";
            /** @enum {string} */
            productFamily?: "picture_book_fixed_layout" | "chapter_book_reflowable";
            /** @description Narrative spread count for picture books. One spread renders as two physical PDF pages. */
            spreadCount: number;
            /** @description Physical PDF page count. Picture-book physical pages equal spreadCount * 2. */
            physicalPageCount: number;
            /** @description Picture-book narrative units. Each array entry represents one spread, not one physical PDF page. */
            pages: {
                /** @description Zero-based spread index retained under the legacy pageIndex field name. */
                pageIndex: number;
                /** @description Zero-based spread index for picture-book readers and reviewers. */
                spreadIndex: number;
                text: string;
                /** @enum {string} */
                status: "pending" | "ready" | "failed";
                imageUrl: string | null;
                previewImageUrl?: string | null;
                templateId?: string | null;
                /** @enum {string} */
                productFamily?: "picture_book_fixed_layout" | "chapter_book_reflowable";
            }[];
        };
        ReviewActionRequest: {
            notes?: string;
        };
        ReviewQueueResponse: {
            cases: {
                /** Format: uuid */
                caseId: string;
                /** @enum {string} */
                status: "open" | "resolved" | "rejected" | "retrying";
                /** @enum {string} */
                stage: "text_moderation" | "image_safety" | "image_qa" | "finalize_gate";
                reasonSummary: string;
                createdAt: string;
                resolvedAt?: string | null;
                /** Format: uuid */
                orderId: string;
                /** @enum {string} */
                orderStatus: "created" | "checkout_pending" | "paid" | "building" | "needs_review" | "ready" | "failed" | "refunded";
                /** Format: uuid */
                bookId: string;
                /** @enum {string} */
                bookStatus: "draft" | "building" | "needs_review" | "ready" | "failed";
                childFirstName: string;
                /** @enum {string} */
                readingProfileId: "read_aloud_3_4" | "early_decoder_5_7" | "independent_8_10";
                /** @enum {string} */
                moneyLessonKey: "prices_change" | "jar_saving_limits" | "new_money_unfair" | "keep_what_you_earn" | "better_rules";
                /** @enum {string} */
                storyMode: "sound_money_implicit" | "bitcoin_reveal_8020" | "bitcoin_forward";
                /** @description Narrative spread count for the book under review. */
                pageCount: number;
                /** @enum {string|null} */
                latestAction?: "approve_continue" | "reject" | "retry_page" | null;
                latestReviewerEmail?: string | null;
            }[];
        };
        ReviewCaseDetailResponse: {
            /** Format: uuid */
            caseId: string;
            /** @enum {string} */
            status: "open" | "resolved" | "rejected" | "retrying";
            /** @enum {string} */
            stage: "text_moderation" | "image_safety" | "image_qa" | "finalize_gate";
            reasonSummary: string;
            reason: {
                [key: string]: unknown;
            };
            createdAt: string;
            resolvedAt?: string | null;
            order: {
                /** Format: uuid */
                orderId: string;
                /** @enum {string} */
                status: "created" | "checkout_pending" | "paid" | "building" | "needs_review" | "ready" | "failed" | "refunded";
            };
            book: {
                /** Format: uuid */
                bookId: string;
                /** @enum {string} */
                status: "draft" | "building" | "needs_review" | "ready" | "failed";
                childFirstName: string;
                /** @enum {string} */
                readingProfileId: "read_aloud_3_4" | "early_decoder_5_7" | "independent_8_10";
                /** @enum {string} */
                moneyLessonKey: "prices_change" | "jar_saving_limits" | "new_money_unfair" | "keep_what_you_earn" | "better_rules";
                /** @enum {string} */
                storyMode: "sound_money_implicit" | "bitcoin_reveal_8020" | "bitcoin_forward";
                /** @description Narrative spread count for picture books. */
                spreadCount: number;
                /** @description Physical PDF page count. Picture-book physical pages equal spreadCount * 2. */
                physicalPageCount: number;
            };
            /** @description Signed URL for the final illustrated PDF when the book has passed all release gates. */
            pdfUrl: string | null;
            /** @description Signed URL for the readable story proof PDF built from story text only. */
            storyProofPdfUrl: string | null;
            scenePlan: {
                url: string | null;
                createdAt: string;
            } | null;
            imagePlan: {
                url: string | null;
                createdAt: string;
            } | null;
            artifacts: {
                artifactType: string;
                url: string | null;
                createdAt: string;
            }[];
            evaluations: {
                stage: string;
                modelUsed: string;
                verdict: string;
                notes?: string | null;
                score: {
                    [key: string]: unknown;
                };
                createdAt: string;
            }[];
            events: {
                /** Format: uuid */
                id: string;
                /** Format: email */
                reviewerEmail: string;
                /** @enum {string} */
                action: "approve_continue" | "reject" | "retry_page";
                notes?: string | null;
                /** Format: uuid */
                pageId?: string | null;
                metadata: {
                    [key: string]: unknown;
                };
                createdAt: string;
            }[];
            pages: {
                /** Format: uuid */
                pageId: string;
                pageIndex: number;
                spreadIndex: number;
                /** @enum {string} */
                status: "pending" | "ready" | "failed";
                text: string;
                templateId?: string | null;
                previewImageUrl: string | null;
                pageArtUrl: string | null;
                latestQaIssues: string[];
                qaMetrics: {
                    [key: string]: unknown;
                } | null;
                provenance: {
                    [key: string]: unknown;
                };
                retryCount: number;
            }[];
        };
        ReviewActionResponse: {
            ok: boolean;
            /** Format: uuid */
            caseId: string;
            /** Format: uuid */
            pageId?: string;
            /** @enum {string} */
            status: "retrying" | "rejected";
            executionArn?: string | null;
        };
        DownloadResponse: {
            /** Format: uri */
            url: string;
            expiresInSeconds: number;
        };
        DeleteChildProfileResponse: {
            ok: boolean;
            /** Format: uuid */
            childProfileId: string;
            /** Format: uuid */
            privacyEventId: string;
            queuedArtifacts: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
